# General
DEBUG = True

# AI
BATCH_SIZE = 16
VERSION = "v0.3"
ANIMALS_NAMES_PATH = "./animals.txt"
ANIMALS_IMAGES_PATH = "./animals_v02"
PREDICTION_IMAGES_PATH = "./animals_prediction"
NUM_ANIMALS = 90
TRAIN_IMAGES_PER_ANIMALS = 200
VALIDATION_IMAGES_PER_ANIMALS = 50

# Scraper
MIN_IMAGE_SIZE_THRESHOLD = 5000 # Bytes