# General
DEBUG = True

# AI
BATCH_SIZE = 16
VERSION = "v0.3"
ENTITIES_DB_VERSION = "v0.2"
ENTITIES_DB_FOLDER = "animals_v0.2"
ENTITIES_NAMES_PATH = "entities.txt"
PREDICTION_IMAGES_PATH = "animals_prediction_v0.2"
NUM_ENTITES = 90
TRAIN_IMAGES_PER_ENTITIES = 200
VALIDATION_IMAGES_PER_ENTITES = 50

# Scraper
MIN_IMAGE_SIZE_THRESHOLD = 5000 # Bytes
