# General
DEBUG = True

IMAGES_PATH = "images/"

MODEL_VERSIONS_PATH = "model/versions/"
MODEL_LAST_VERSION = "v0.3"

ENTITIES_NAMES_PATH = "config/entities.txt"
ENTITIES_DB_PATH = f"{IMAGES_PATH}entities/"
ENTITIES_DB_VERSION = "v0.2" # Must be deleted for a single version

TRAIN_IMAGES_PATH = f"{ENTITIES_DB_PATH}train/"
VALIDATION_IMAGES_PATH = f"{ENTITIES_DB_PATH}validation/"
EVALUATION_IMAGES_PATH = f"{ENTITIES_DB_PATH}evaluation/"

# AI
BATCH_SIZE = 16
NUM_ENTITIES = 90
TRAIN_IMAGES_PER_ENTITIES = 200
VALIDATION_IMAGES_PER_ENTITIES = 50

# Scraper
MIN_IMAGE_SIZE_THRESHOLD = 5000 # Bytes
